# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mldev < Formula
  desc "Tools for Mosaic Learning developers and engineers."
  homepage "https://mosaiclearning.com/"
  version "0.1.5"

  depends_on "git"
  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sbhrule15/brew/releases/download/v0.1.5/mldev_Darwin_arm64.tar.gz"
      sha256 "9797b1c6e68fd93fd186cf6edffb3b4ee0c9d72b6a2e6c1dd8e1d9313e04de6d"

      def install
        bin.install "mldev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sbhrule15/brew/releases/download/v0.1.5/mldev_Darwin_x86_64.tar.gz"
      sha256 "923aba4a80d59f6d7887976e272023b298fae2d6b4d04b718ae5fe168c4b8d8c"

      def install
        bin.install "mldev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbhrule15/brew/releases/download/v0.1.5/mldev_Linux_arm64.tar.gz"
      sha256 "97c2de5507893e54b498a1813bc9c6235fdd40ba027d68f924449f21e55f3d84"

      def install
        bin.install "mldev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sbhrule15/brew/releases/download/v0.1.5/mldev_Linux_x86_64.tar.gz"
      sha256 "8c2c020f3b033a375f7e13352820328c453df0b16114dde2a1f3659aa8654e9b"

      def install
        bin.install "mldev"
      end
    end
  end
end
